### ISSUE TITLE
swait signal is not automatically updated when requested

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#115]
reported by @kedokudo

When using the user_calcs (relying on the swait record support in apstools), the signal is not automatically updated when requested.  Instead, we need to rerun the (definition) cell to get an updated value.

- how can we get the automatically updated signal from EpicsSignalRO every time we evaluate the corresponding instance?
- is it possible to get a switch to toggle the monitor of all EpicsSignal? This could be useful when we implement jupyter-dashboard for 6-ID-D.

**Comment by prjemian** [comment]
| how can we get the automatically updated signal ...?

Try using signal_object`.get()` instead of signal_object`.value`

**Comment by prjemian** [comment]
| is it possible to get a switch to toggle the monitor of all EpicsSignal?

If I understand the question, you want to choose whether or not to monitor all the EpicsSignal objects during a scan?

The choice of whether or not to monitor is user-controllable so the answer is yes.  But, since there is no [central registry of ophyd objects](https://github.com/NSLS-II/ophyd/issues/588), the job is a bit harder since each Signal or Device will need to be subscribed separately.  Each subscription will create its own event stream (since the exact timing of EPICS updates will likely be independent of each other).  The process might be simplified by creating your own registry and then a function can handle the subscribe and unsubscribe actions.

**Comment by KedoKudo** [comment]
> | how can we get the automatically updated signal ...?
> 
> Try using signal_object`.get()` instead of signal_object`.value`

I will try this method out during our next test.

**Comment by KedoKudo** [comment]
> | is it possible to get a switch to toggle the monitor of all EpicsSignal?
> 
> If I understand the question, you want to choose whether or not to monitor all the EpicsSignal objects during a scan?
> 
> The choice of whether or not to monitor is user-controllable so the answer is yes. But, since there is no [central registry of ophyd objects](https://github.com/NSLS-II/ophyd/issues/588), the job is a bit harder since each Signal or Device will need to be subscribed separately. Each subscription will create its own event stream (since the exact timing of EPICS updates will likely be independent of each other). The process might be simplified by creating your own registry and then a function can handle the subscribe and unsubscribe actions.

I was thinking about getting a button/function that will pause the monitoring of all EpicsSignals and return a quick summary of all the requested signals to the frontend so that the user can make a comprehensive decision for the next step.  After making the decision, the user can resume the monitoring of all PVs as before.  Is there something similar that has already been implemented in apstools?

**Comment by prjemian** [comment]
Not exactly.  Most parts are probably available from bluesky.  A [suspender](http://nsls-ii.github.io/bluesky/state-machine.html#suspenders) can be used to create the pause (by [watching an EPICS PV used to trigger the suspender](http://nsls-ii.github.io/bluesky/generated/bluesky.suspenders.SuspendBoolHigh.html#bluesky.suspenders.SuspendBoolHigh)) and probably make the on-screen report.  The user would then make the choice to RE.stop(), RE.abort(), RE.resume(), or RE.halt() as part of the comprehensive decision.  Whether or not this suspends signal monitoring, we can take a look at it.

**Comment by KedoKudo** [comment]
The __bluesky_snapshot__ can provide most of the functionality needed, so I think we can close this issue for now. :)

**Comment by prjemian** [comment]
Ok
