### ISSUE TITLE
use named table in Excel spreadsheet, if it exists

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#122]
Excel has an option to refer to a 2-D grid using a single name, as defined using the `Format as Table` selection within Excel.  Issue #116 would be improved if the named table was exposed through either [pandas](https://pandas.pydata.org/),  [xlrd](https://xlrd.readthedocs.io), or [xlutils](https://xlutils.readthedocs.io) but none of those packages seem to expose this feature of an Excel `.xlsx` spreadsheet file.

**Comment by prjemian** [comment]
The description of named tables and sheet pages in an Excel `.xlsx` file is distributed.  The `.xlsx` file is a ZIP archive containing subdirectories and XML files.  Here we consider the contents of the unzipped `spreadsheet.xlsx` file as a directory.

## sheets and named ranges

The *named ranges* (not what we need here, at least for now) are listed in `spreadsheet.xlsx\xl\workbook.xml` in element `workbook/definedNames` as such:

	<sheets>
		<sheet name="sample data" sheetId="1" r:id="rId1"/>
		<sheet name="demo" sheetId="2" r:id="rId2"/>
	</sheets>
	<definedNames>
		<definedName name="example_code">demo!$B$5:$B$9</definedName>
		<definedName name="example_output">demo!$B$12:$B$16</definedName>
	</definedNames>

where `demo` is the name of sheet 2.

## relationships between sheets and tables

The tables for each sheet are specified in `.xml.rels` files in directory: `spreadsheet.xlsx\xl\_rels\`

Here is an example for *sheet1* (`spreadsheet.xlsx\xl\_rels\sheet1.xml.rels`):

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships 
    xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
	<Relationship Id="rId2" 
            Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" 
            Target="../tables/table2.xml"/>
	<Relationship  Id="rId1" 
            Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" 
            Target="../tables/table1.xml"/>
</Relationships>
```

## table specifications

Elsewhere in the `.xlsx` file, the list of named tables is in the directory: `spreadsheet.xlsx\xl\tables\`where a separate `.xml` file is used for each table specification.  Here is an example:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" 
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    mc:Ignorable="xr xr3" 
    xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision" 
    xmlns:xr3="http://schemas.microsoft.com/office/spreadsheetml/2016/revision3" 
    id="1" 
    xr:uid="{5CED485F-BCAA-442F-972F-86184824212F}" 
    name="Table1" 
    displayName="Table1" 
    ref="A4:G10" 
    totalsRowShown="0">
	<autoFilter ref="A4:G10" xr:uid="{7B8E28EA-08B3-4BE0-B34B-55C4BA285823}"/>
	<tableColumns count="7">
		<tableColumn 
                        id="1" 
                        xr3:uid="{CA68B4B7-C326-4B5A-A090-BA441CAAECE6}" 
                        name="Scan Type"/>
		<tableColumn id="2"
                         xr3:uid="{2CD5FF68-71AC-4CF3-AF1D-0434B0383874}" 
                        name="sx"/>
		<tableColumn id="3" 
                        xr3:uid="{997DBA11-B148-4A03-8D0C-BAFE90989855}" 
                        name="sy"/>
		<tableColumn id="4" 
                        xr3:uid="{157BAE2D-14B8-4812-A872-DE95FA2B7E96}" 
                        name="Thickness"/>
		<tableColumn id="5" 
                        xr3:uid="{4F8B901A-2743-4669-9294-B718A19066C0}" 
                        name="Sample Name"/>
		<tableColumn id="6" 
                        xr3:uid="{996924C8-6431-4904-9104-AC793A826DA0}" 
                        name="remarks"/>
		<tableColumn  id="7" 
                        xr3:uid="{48D04D1E-1811-4669-9402-D76FE8609231}" 
                        name="code number"/>
	</tableColumns>
	<tableStyleInfo name="TableStyleMedium2" 
	    showFirstColumn="0" 
	    showLastColumn="0" 
	    showRowStripes="1" 
	    showColumnStripes="0"/>
</table>```

**Comment by prjemian** [comment]
How fragile is this analysis?  Will it work with Excel files written by other software or by other versions of Excel?  Might be more robust to expect the caller to *name* the sheet and cell range (including column labels).

**Comment by prjemian** [comment]
How about using [pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html)?  Maybe this work is done for us.

**Comment by 0ignaci0** [comment]
I've done some research on this and put together a script [checkTables](https://github.com/0ignaci0/checkTables) that will load a workbook, look for tables on each worksheet, and if there are tables, saves the table info to a dictionary keyed by the table name, which then is placed into another dictionary keyed by worksheet name. 
pandas does not have this functionality out of the box (reading in tables into data frames, although there was a [pull request](https://github.com/pandas-dev/pandas/pull/24899) that never got completed for this function), but once the table info is in a dictionary, it's pretty simple to convert it to a data frame.
The checkTables script uses openpyxl, which includes a "._tables" object for each worksheet, where all the pertinent info lives (table name and table location/reference for indexing to retrieve cell contents). 
Let me know how I can help integrate this script towards the goal of this enhancement!

**Comment by prjemian** [comment]
Might be much easier with [openpyxl](https://openpyxl.readthedocs.io/en/stable/).  Started using that in #472.
