### ISSUE TITLE
special handling for spec2ophyd, CNTPAR with misc_par_1 

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#197]
Similar to #196, replaces part of the counter's full PV name

**Comment by prjemian** [comment]
Nice to have an example of this.

**Comment by jkirchman** [comment]
Here's an example from 12BM. I had to rename it to config.txt so it would let me attach it. They use a number of these CNTPAR to set up different counters from a 3820 Struck. Note that they also have some additional devices listed (serial, GPIB, etc) which are directly controlled by SPEC.

[config.txt](https://github.com/BCDA-APS/apstools/files/3432856/config.txt)
