### ISSUE TITLE
AttributeError from db.hs

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#315]
This line: https://github.com/BCDA-APS/apstools/blob/master/apstools/examples.py#L63 generates this error:

```
AttributeError: hs
```

Comes from here:  https://github.com/bluesky/databroker/blob/0366a8925d50076de7ab9327fcc7e9e19dc8fd57/databroker/_core.py#L902-L912

which means this must change due to changes in databroker

**Comment by danielballan** [comment]
It looks like our tests didn't cover this, so it was passed over in our efforts to make `databroker.v1.Broker` match the API of `databroker.v0.Broker`. If you think this will come up many places, we can add an `hs` accessor to match the v0 API, but if changing `db.hs.find_run_starts` to `db()` (the standard v1 way) or `db.v2.search` (the recommended v2 way) fixes the issue, that would be the easier path for us.

**Comment by prjemian** [comment]
Since `apstools.utils.listruns()` provides this capability, the example function should be removed.
