### ISSUE TITLE
epid final_value signal not found

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#325]
When using the `epid` object at APS 8-ID-I, we did not find the `final_value` (`.VAL`) signal.

**Comment by prjemian** [comment]
The class is defined:

https://github.com/BCDA-APS/apstools/blob/8fbbbd977f33270c55d62e8d1758f6b5e116d1ec/apstools/synApps/epid.py#L34

**Comment by prjemian** [comment]
epid record documentation: https://cars9.uchicago.edu/software/epics/epidRecord.html

**Comment by MarkRivers** [comment]
The documentation appears to be wrong.  It says that the CT field is a ULONG in clock ticks, and that it is accessible from Channel Access.  

However, this is from the epidRecord.dbd file:
```
        field(CT,DBF_NOACCESS) {
                prompt("Time")
                special(SPC_NOMOD)
                interest(4)
                extra("epicsTimeStamp  ct")
        }
        field(CTP,DBF_NOACCESS) {
                prompt("Previous time")
                special(SPC_NOMOD)
                interest(4)
                extra("epicsTimeStamp   ctp")
        }

```
So CT is in fact it is an epicsTimeStamp structure with the attribute DBF_NOACCESS.

Source code never lies :-).

**Comment by prjemian** [comment]
You (re)teach a valuable lesson today.

**Comment by prjemian** [comment]
In *this* issue, the object created in a bluesky session does not show the `final_value` attribute that should be connected to the `.VAL` field of the attribute.  I wrote that instruction assuming the connection should come from the superclass `EpicsRecordDeviceCommonAll` as it is defined here: https://github.com/BCDA-APS/apstools/blob/56cd7ce806e7c50639e113afc6cf3c5b5e432af9/apstools/synApps/_common.py#L41-L63

But this is my mistake since the `.VAL` field is provided in a different mixin class: https://github.com/BCDA-APS/apstools/blob/56cd7ce806e7c50639e113afc6cf3c5b5e432af9/apstools/synApps/_common.py#L66-L78

and this class is not included in the definition of the epid support here: https://github.com/BCDA-APS/apstools/blob/56cd7ce806e7c50639e113afc6cf3c5b5e432af9/apstools/synApps/epid.py#L34

**Comment by prjemian** [comment]
The `.VAL` field is not common to all EPICS records?

Apparently not: https://wiki-ext.aps.anl.gov/epics/index.php/RRM_3-14_dbCommon

**Comment by MarkRivers** [comment]
The common record fields need to have the same type in every record.  VAL does not, since it might be a double, a string, or an array of some type depending on the record.

**Comment by prjemian** [comment]
That underscores the finding that `EpicsRecordInputFields` is not a good superclass mixin for this support.  It defines an `RVAL` field that is not available in the `epid` record.

The `.VAL` field will be added directly to the `EpidRecord` definition.

**Comment by prjemian** [comment]
... as a read-only signal: `final_value = Component(EpicsSignalRO, ".VAL")`

with `final_value` to match similar usage in `EpicsRecordInputFields`
