### ISSUE TITLE
add Y & Z motor to KohzuSeqCtl_Monochromator

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#402]
In https://github.com/APS-4ID-POLAR/ipython-polar/pull/14/files/c39b456ec45e141f9283c1f0db0f57d9d5650792#diff-7de6a16b1df04d790e6aa7c1e596b0ad, local additions to access the Y & Z motors of the Kohzu monochromator code.  We should pull that in here.

Thanks @gfabbris!

**Comment by gfabbris** [comment]
The current setup has theta as an EpicsSignal looking at the pv in the Kohzu window. I wonder if it'd be better to use it as an EpicsMotor. Note that the Kohzu window reports the theta, y, and z PVs. So I modified the way things are defined in the [POLAR mono setup](https://github.com/APS-4ID-POLAR/ipython-polar/blob/motors_setup/profile_bluesky/startup/instrument/devices/monochromator.py), so that it reads the local motor PVs from the standard Kohzu window, and defines them as EpicsMotors. What do you think?

As far as I can tell, the Kohzu window doesn't read the theta_fine and chi motors, so those will need to be added separately.

**Comment by prjemian** [comment]
The underlying controls access the Kohzustate notation language (sequence) control program and database.  The apstools device talks to this support which, in turn, talks to the actual parts (motors, et al.).

Here's where Y & Z PVs are defined for the GUI screen:

https://github.com/epics-modules/optics/blob/3475b430ea82565f614e0582d10055824c77f465/opticsApp/Db/kohzuSeq.db#L275-L280

![Clipboard02](https://user-images.githubusercontent.com/2279984/91207082-d259b500-e6cd-11ea-9e96-d826252772a7.png)

**Comment by prjemian** [comment]
If our python object talks to the motors directly, we bypass the IOC's monochromator support.  We should not do that, but rather keep this object a _thin_ interface to the EPICS controls.

**Comment by prjemian** [comment]
@gfabbris Yes, I was thinking of getting the motor PV name from the Kohzu support.  I'll look later today to see what you have done.

**Comment by prjemian** [comment]
Is there a way to avoid importing pyepics to get those values?  Probably more bother to create ophyd objects to do the same.

**Comment by gfabbris** [comment]
> If our python object talks to the motors directly, we bypass the IOC's monochromator support. We should not do that, but rather keep this object a _thin_ interface to the EPICS controls.

I think you raise a good point in that it may be better to not skip over the controls that are implemented in the Kohzu screen. This is particularly true for the y and z motors, as in standard operations we don't want to be able to just move them, so it may be better to have them as `EpicsSignalRO`. 

I also just realized that if we move the theta as `EpicsMotor`, this screen sees it as an error, and switches over to _Manual_. This won't happen if it is setup as an `EpicsSignal`. Note however that this shouldn't be a big issue because I added a "click the _Auto_" to the mono.stage_sigs.

This is all to say that I'm actually more inclined now to have _theta_ as an `EpicsSignal` (as you have it currently setup), and _y_ and _z_ as `EpicsSignalRO`, so that it's recorded, but cannot be independently moved.

> Is there a way to avoid importing pyepics to get those values? Probably more bother to create ophyd objects to do the same.

The only way I can think is to add this in the `__init__`:
`self._theta_pv = EpicsSignal(prefix+'KohzuThetaPVSI').get()`
I think this way it'd get the value, but wouldn't create an attribute.

**Comment by prjemian** [comment]
Likely that `self._theta_pv = EpicsSignal(prefix+'KohzuThetaPVSI').get()` would provoke connection timeouts on occasion.  For the same reason, I'm concerned that this code might also fail on occasion:

```
    th = FormattedComponent(EpicsMotor,'{self._theta_pv}',
                            labels=('motor','monochromator'))  # Kohzu Theta
    
    y = FormattedComponent(EpicsMotor,'{self._y_pv}',
                            labels=('motor','monochromator'))   # Kohzu Y2
    
    z = FormattedComponent(EpicsMotor,'{self._z_pv}',
                            labels=('motor','monochromator'))  # Kohzu Z2
```

**Comment by gfabbris** [comment]
Ok. What about this:

```
theta = Component(EpicsSignal, "BraggThetaRdbkAO", write_pv="BraggThetaAO") #This is already in __KohzuSeqCtl_Monochromator__
y = Component(EpicsSignalRO,"KohzuYRdbkAI")
z = Component(EpicsSignalRO,"KohzuZRdbkAI")
```

As I mentioned, we certainly also need _chi_ and _thf_ motors at 4IDD, but I don't know how general these are at other beamline's. There are also a few other Kohzu motors that we never use, but it may be a good idea to keep a record of it.

**Comment by prjemian** [comment]
The _chi_ and _thf_ axes are not common to all Kohzu DMCs.  Some even have a second crystal bender for sagittal focus.  These are local mods to the standard support.  Best not to reserve a name here for axes that may not be used (or other names might be used).

**Comment by prjemian** [comment]
I like the idea of instrumenting just the _Y_ and _Z_ readback signals only.  Just built an IOC with a Kohzu monochromator simulator to test.

**Comment by prjemian** [comment]
Also, unless there is a strong preference, bluesky startup should be cautious about changing EPICS PVs directly, such as:

```
mono.mode.put('Auto')                   # Switch mono to "auto".
mono.stage_sigs['mode'] = "Auto"             # Ensure that mono is in auto before moving.
```

If `mono.mode.put('Auto')` is executed, then bluesky startup will immediately affect the monochromator, even if some other code is using it.  Startup should be passive.  Think of the case where someone is running the beamline while someone else is developing code or troubleshooting.  The developer's actions would interfere with operations.

**Comment by gfabbris** [comment]
We will probably to use the `moveE` plan to change energy, which stages the mono, so the `mono.mode.put('Auto')` is actually useless. 

But this may cause problems if one tries to move the energy directly (with something like `bps.mv(mono.energy,target_energy)`), because `bps.mv` won't stage the _mono_, so the energy will not move if the _mode_ is not _Auto_. One solution would be to tweak the `mono.energy.put()` to add a "click _Move_" command.

**Comment by prjemian** [comment]
mono.move_button.put(1)

```
In [12]: object_explorer(mono)                                                                                                                    
======================== ===================== ==================
name                     PV reference          value             
======================== ===================== ==================
chi.acceleration         dcm:m5.ACCL           0.2               
chi.direction_of_travel  dcm:m5.TDIR           0                 
chi.high_limit_switch    dcm:m5.HLS            0                 
chi.high_limit_travel    dcm:m5.HLM            32000.0           
chi.home_forward         dcm:m5.HOMF           0                 
chi.home_reverse         dcm:m5.HOMR           0                 
chi.low_limit_switch     dcm:m5.LLS            0                 
chi.low_limit_travel     dcm:m5.LLM            -32000.0          
chi.motor_done_move      dcm:m5.DMOV           1                 
chi.motor_egu            dcm:m5.EGU            degrees           
chi.motor_is_moving      dcm:m5.MOVN           0                 
chi.motor_stop           dcm:m5.STOP           0                 
chi.offset_freeze_switch dcm:m5.FOFF           0                 
chi.set_use_switch       dcm:m5.SET            0                 
chi.user_offset          dcm:m5.OFF            0.0               
chi.user_offset_dir      dcm:m5.DIR            0                 
chi.user_readback        dcm:m5.RBV            0.0               
chi.user_setpoint        dcm:m5.VAL            0.0               
chi.velocity             dcm:m5.VELO           1.0               
crystal_2d_spacing       dcm:Bragg2dSpacingAO  6.271201717948483 
crystal_h                dcm:BraggHAO          1.0               
crystal_k                dcm:BraggKAO          1.0               
crystal_l                dcm:BraggLAO          1.0               
crystal_lattice_constant dcm:BraggAAO          5.43102           
crystal_mode             dcm:KohzuMode2MO      0                 
crystal_type             dcm:BraggTypeMO       0                 
energy                   dcm:BraggERdbkAO      8.119949320912882 
message1                 dcm:KohzuSeqMsg1SI                      
message2                 dcm:KohzuSeqMsg2SI                      
mode                     dcm:KohzuModeBO       0                 
move_button              dcm:KohzuPutBO        0                 
operator_acknowledge     dcm:KohzuOperAckBO    0                 
theta                    dcm:BraggThetaRdbkAO  14.092            
thf.acceleration         dcm:m4.ACCL           0.2               
thf.direction_of_travel  dcm:m4.TDIR           0                 
thf.high_limit_switch    dcm:m4.HLS            0                 
thf.high_limit_travel    dcm:m4.HLM            32000.0           
thf.home_forward         dcm:m4.HOMF           0                 
thf.home_reverse         dcm:m4.HOMR           0                 
thf.low_limit_switch     dcm:m4.LLS            0                 
thf.low_limit_travel     dcm:m4.LLM            -32000.0          
thf.motor_done_move      dcm:m4.DMOV           1                 
thf.motor_egu            dcm:m4.EGU            degrees           
thf.motor_is_moving      dcm:m4.MOVN           0                 
thf.motor_stop           dcm:m4.STOP           0                 
thf.offset_freeze_switch dcm:m4.FOFF           0                 
thf.set_use_switch       dcm:m4.SET            0                 
thf.user_offset          dcm:m4.OFF            0.0               
thf.user_offset_dir      dcm:m4.DIR            0                 
thf.user_readback        dcm:m4.RBV            0.0               
thf.user_setpoint        dcm:m4.VAL            0.0               
thf.velocity             dcm:m4.VELO           1.0               
use_set                  dcm:KohzuUseSetBO     0                 
wavelength               dcm:BraggLambdaRdbkAO 1.5269090864973665
y                        dcm:KohzuYRdbkAI      -18.043           
y_offset                 dcm:Kohzu_yOffsetAO   17.5              
z                        dcm:KohzuZRdbkAI      71.875            
======================== ===================== ==================
```

**Comment by prjemian** [comment]
Pressing `move_button` when in Auto mode toggles the `dcm:KohzuMving` PV on, then off, otherwise benign.  Add this class method:

```
    def move_energy(self, energy):
        """for command-line use:  mono.energy_move(8.2)"""
        self.energy.put(energy)
        self.move_button.put(1)
```

**Comment by prjemian** [comment]
```python
class Monochromator(KohzuSeqCtl_Monochromator):
    
    y = Component(EpicsSignalRO, "KohzuYRdbkAI")
    z = Component(EpicsSignalRO, "KohzuZRdbkAI")
    
    thf = Component(EpicsMotor,'m4',labels=('motor','monochromator'))  # Kohzu Th2f
    chi = Component(EpicsMotor,'m5', labels=('motor','monochromator'))  # Kohzu Chi

    def move_energy(self, energy):
        """for command-line use:  mono.energy_move(8.2)"""
        self.energy.put(energy)
        self.move_button.put(1)
```

**Comment by prjemian** [comment]
I'll this to apstools, without the `thf` and `chi` since those variations are not part of the Kohzu database.

**Comment by gfabbris** [comment]
Looks good

**Comment by prjemian** [comment]
I like this, too.  Far simpler than other ideas.  Still, I want to test your idea with the `caget()`, just to see how well it would work.  We are only lucky this monochromator support even has an interface for the _Y1_ and _Z2_ motors.  It is tempting to name these `y1` & `z2` since they are motions on crystals 1 & 2, respectively.  33BM & 33ID use these names, for example.
