### ISSUE TITLE
AD support from USAXS

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#419]
The USAXS is using some additional [AreaDetector support](https://github.com/APS-USAXS/ipython-usaxs/blob/360c37251feeaef9e0ff84dcef1fe6a812e46f15/profile_bluesky/startup/instrument/devices/for_apstools.py) that could be added to the `apstools` package.

code | docstring
--- | ---
`AD_EpicsJpegFileName` | custom class to define image file name from EPICS
`AD_plugin_primed` | Has area detector pushed an NDarray to the file writer plugin?  True or False
`AD_prime_plugin` | Prime this area detector's file writer plugin.

**Comment by MarkRivers** [comment]
Note that the "prime" functions are not needed if you select the "LazyOpen" for the file plugin.

**Comment by prjemian** [comment]
Mark
What minimum version of AD is needed for this support?

**Comment by MarkRivers** [comment]
This is from the ADCore/RELEASE.md file
```
R2-1 (October 17, 2014)
NDPluginFile
Added new optional feature "LazyOpen" which, when enabled and in "Stream" mode, will defer file creation until the first frame
arrives in the plugin. This removes the need to initialize the plugin with a dummy frame before starting capture.
```

**Comment by prjemian** [comment]
Nice!
