### ISSUE TITLE
Need robust method to check if AD plugin is primed

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#464]
AD plugins need to be primed if the plugin configuration does not match the cam configuration that will be emitted.  Any writer, not just the HDF5 writer.

**Comment by MarkRivers** [comment]
> AD plugins need to be primed if the plugin configuration does not match the cam configuration that will be emitted. Any writer, not just the HDF5 writer.

That is not true if you set LazyOpen=1.  This waits to open the file until the first real image is received, rather than doing it immediately when Streaming is started.  This feature has been available since ADCore R2-1 in 2014.

The only downside is that the overhead of opening the file can mean that additional frames may need to be queued when streaming starts.  But this is easily accomplished by making the queue size large enough.

**Comment by MarkRivers** [comment]
Look for "lazy" on this page: https://areadetector.github.io/master/ADCore/NDArray.html#asynndarraydriver

**Comment by prjemian** [comment]
The `LazyOpen` feature sounds great but still, some workflows need to control the number of images generated.  Which means we still want a robust test procedure.  As I understand it, the test for *primed* needs to satisfy:

* cam array_size is non-zero
* plugin array_size is non-zero
* cam & plugin array_size match
* cam & plugin color_mode match
* cam & plugin data_type match

**Comment by prjemian** [comment]
This code implements those conditions in ophyd:

```python
def ad_plugin_primed(plugin):
    """
    Is the area detector 'det' plugin primed?

    PARAMETERS
    ----------
    plugin
        obj :
        ophyd AreaDetector plugin instance

    PARAMETERS
    ----------
    bool :
        True if plugin is primed
    """
    cam = plugin.parent.cam
    tests = []

    for obj in (cam, plugin):
        test = np.array(obj.array_size.get()).sum() != 0
        tests.append(test)
        if not test:
            logger.debug("'%s' image size is zero", obj.name)

    checks = dict(
        array_size = False,
        color_mode = True,
        data_type = True,
    )
    for key, as_string in checks.items():
        c = getattr(cam, key).get(as_string=as_string)
        p = getattr(plugin, key).get(as_string=as_string)
        test = c == p
        tests.append(test)
        if not test:
            logger.debug("%s does not match", key)

    return False not in tests
```

**Comment by MarkRivers** [comment]
> The LazyOpen feature sounds great but still, some workflows need to control the number of images generated.

I don't understand that comment.  With LazyOpen you still have complete control over the number of images generated.

If you use LazyOpen there is no need to check any matches of the cam and the plugin, they are guaranteed to match when the first array arrives.  You may still need to check that cam_size is not 0.

**Comment by prjemian** [comment]
Fair enough.  I'll try it with the USAXS.

**Comment by prjemian** [comment]
BTW, my comment about some workflows was in response to my understanding of:

> The only downside is that the overhead of opening the file can mean that additional frames may need to be queued when streaming starts. But this is easily accomplished by making the queue size large enough.
