### ISSUE TITLE
Request for common device support

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#489]
Request from an APS beam line:
    
> There are too little or no hardware support in the https://blueskyproject.io/ophyd/. It seems still lot of programming needs to be done. Do you have a page for various devices used at APS. I need a dg645, PTC10, linkam, pilatus, perkinElmer detector. If not, I may start to use it just for scanning.

**Comment by prjemian** [comment]
* [ ] create an issue for DG645
* [ ] create an issue for PTC10
* [ ] create an issue for Linkam
* [ ] document example to support a Pilatus detector
* [ ] document example to support a PerkinElmer detector
* [ ] Create documentation index entries for supported devices.

**Comment by prjemian** [comment]
USAXS has Pilatus support that can be made into an example: https://github.com/APS-USAXS/ipython-usaxs/blob/master/profile_bluesky/startup/instrument/devices/pilatus_module.py

**Comment by prjemian** [comment]
Ophyd has a [`PerkinElmerDetector`](https://github.com/bluesky/ophyd/blob/master/ophyd/areadetector/detectors.py#L165-L167) class, so support for that should be similar to any other AD in ophyd.

**Comment by gfabbris** [comment]
This is a good point. In my experience, we need to do quite a bit of tweaking even for detectors that have some support in ophyd (like the xspress3).

**Comment by prjemian** [comment]
Can close this once the docs [build](https://readthedocs.org/projects/apstools/builds/12825048/) and the `Example; Area Detector` entries appear in the [index](https://apstools.readthedocs.io/en/latest/genindex.html#E).

**Comment by canismarko** [comment]
I noticed the DG-645 is listed here but I don't see any issues or commits that add it. Happy to do it myself, just checking before I get started in case it's been done already. Thanks!

**Comment by prjemian** [comment]
@canismarko: Your DG645 contribution would be most welcome!

**Comment by canismarko** [comment]
Submitted a PR that would add support for the DG-645: https://github.com/BCDA-APS/apstools/pull/877
