### ISSUE TITLE
Device for lakeshores temperature controllers

### ISSUE THREAD

**Issue by gfabbris** [BCDA-APS/apstools#493]
I believe most beamlines from the MM and IXN groups use the lakeshore 340. At 4-ID-D we also have the 336. The 4ID-POLAR setup has the setup for both ([340](https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/lakeshore340.py), [336](https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/lakeshore336.py)), but it could probably be tweaked for generality.

**Comment by prjemian** [comment]
beam line | ophyd support
--- | ---
APS Polar 4-ID-C | [LakeShore 340](https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/lakeshore340.py)
APS Polar 4-ID-C | [LakeShore 336](https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/lakeshore336.py)
APS XPCS 8_ID-I | [LakeShore 336](https://github.com/aps-8id-dys/ipython-8idiuser/blob/fc17d6e442c354ea53202ff8184cc7a7c0a00e87/profile_bluesky/startup/instrument/devices/lakeshore.py)

**Comment by prjemian** [comment]
@gfabbris , @qzhang - There are some differences between [XPCS](https://github.com/aps-8id-dys/ipython-8idiuser/blob/fc17d6e442c354ea53202ff8184cc7a7c0a00e87/profile_bluesky/startup/instrument/devices/lakeshore.py#L121-L128) and [Polar](https://github.com/APS-4ID-POLAR/ipython-polar/blob/8c185bd85310f159fbeab9352173d8d2c6e5ca1f/profile_bluesky/startup/instrument/devices/lakeshore336.py#L201-L211) implementations of the LakeShore 336 support.   At Polar, loop1 is for control and loop 2 is for the sample, loops 3 & 4 are read-only.  

```python
class LS336Device(Device):
    loop1 = FormattedComponent(LS336_LoopControl, "{prefix}", loop_number=1)
    loop2 = FormattedComponent(LoopSample, "{prefix}", loop_number=2)
    loop3 = FormattedComponent(LS336_LoopRO, "{prefix}", loop_number=3)
    loop4 = FormattedComponent(LS336_LoopRO, "{prefix}", loop_number=4)
```

At XPCS, it's a little less detailed:

```python
class LS336Device(Device):
    loop1 = FormattedComponent(LS336_LoopMore, "{self.prefix}", loop_number=1)
    loop2 = FormattedComponent(LS336_LoopMore, "{self.prefix}", loop_number=2)
    loop3 = FormattedComponent(LS336_LoopBase, "{self.prefix}", loop_number=3)
    loop4 = FormattedComponent(LS336_LoopBase, "{self.prefix}", loop_number=4)
```

Any advice how to proceed?  Is each LakeShore 336 the same or does the user choose what to do with each loop?

**Comment by prjemian** [comment]
A bigger difference that I see is that the 8-ID-I XPCS implementation (`LS336_LoopBase()`) allows loops 3 & 4 to be control loops but 4-ID-C Polar (`LS336_LoopRO()`) treats them as read-only:

```python
class LS336_LoopRO(Device): # Polar
    """
    loop3 and loop4 do not use the heaters.
    """
    readback = FormattedComponent(EpicsSignalRO, "{prefix}IN{loop_number}", kind="normal")


class LS336_LoopBase(ProcessController):  XPCS
    """
    One control loop on the LS336 temperature controller
    
    Each control loop is a separate process controller.
    """
    signal = FormattedComponent(EpicsSignalRO, "{self.prefix}OUT{self.loop_number}:SP_RBV")
    target = FormattedComponent(EpicsSignal, "{self.prefix}OUT{self.loop_number}:SP", kind="omitted")
```

(NOTE: These will be refactored into `apstools.devices.PVPositionerSoftDoneWithStop`.)

**Comment by prjemian** [comment]
In the end, should we have one LakeShore336Device which all can use or does each implementation need to be built from parts (like an area detector support)?

**Comment by prjemian** [comment]
@gfabbris The 340 support looks similarly complicated.  Comment?

**Comment by prjemian** [comment]
Summary, each _loop_ should not be a positioner.  Instead, each loop should have a `temperature` attribute that is a positioner, to provide consistency across all the temperature controllers to be supported.

Other controller features (such as pressure, vacuum, ...) could also be positioners if the controller supports such.

**Comment by prjemian** [comment]
@gfabbris Since this [branch](https://github.com/BCDA-APS/apstools/tree/493-lakeshore) was last edited, there have been [significant changes](https://github.com/BCDA-APS/apstools/blob/main/CHANGES.rst) in the `apstools` repository, [preparing](https://github.com/BCDA-APS/apstools/projects/7) for the  1.6.0 release.

It's time to merge those changes (from the *main* branch) into this branch before continuing.

**Comment by prjemian** [comment]
@gfabbris 

Commit 545a992 belongs here.  It is a new branch, compatible with the refactor for release 1.6, that copies the `lakeshore_controllers.py` file from the original branch.

**Comment by prjemian** [comment]
@gfabbris If you agree the new branch (`493-v2-lakeshore`) covers the work-in-progress now, you can delete the original `493-lakeshore` branch on the [branches](https://github.com/BCDA-APS/apstools/branches) page.

**Comment by gfabbris** [comment]
Looks good, deleting the original branch.
