### ISSUE TITLE
On the use of `EpicsSignal` for a positioner

### ISSUE THREAD

**Issue by gfabbris** [BCDA-APS/apstools#508]
I just realized that `EpicsSignal` does not have a `stop` method. This makes it a bit dangerous to be used in positioners, because there is no internal method to stop an undesired motion.

I'm bringing this up here, because that is currently the case for the motors in [`KohzuSeqCtl_Monochromator`](https://github.com/BCDA-APS/apstools/blob/f54664900c2dbc6572ab644a01fb5a100f0fd2ce/apstools/devices.py#L1572). The EPICS support has an "All Stop" pv, perhaps that can be implemented?

**Comment by prjemian** [comment]
I'll look for the stop on just the monochromator motors.  The all stop is a
blunt tool, more for panic stops.

**Comment by prjemian** [comment]
The [PVPositioner](https://blueskyproject.io/ophyd/reference/positioners.html#pvpositioner) class provides a `stop()` method.  This could be used for (virtual axes) energy, wavelength, and theta to support the KohzuSeqCtl code in EPICS.

Still, this does not detail an easy way to stop *only* the monochromator motors and not stop other motors in the same IOC.  Currently, the *best practice* is to stop all motors in the IOC using the `$(P)allstop` PV (where `$(P)` is the IOC's PV prefix).
