### ISSUE TITLE
SRS570 amplifier

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#541]
Support the SRS570 amplifier.

Is the [preamps support at APS 8IDI](https://github.com/aps-8id-dys/ipython-8idiuser/blob/1198f3131cf971294bea254c1f298416c9fdbbdd/profile_bluesky/startup/instrument/devices/preamps.py#L14-L56) a starting point to be hoisted?

**Comment by prjemian** [comment]
@rodolakis: Thanks for the tip!

**Comment by gfabbris** [comment]
I made a simple support that was targeted at just storing the info, but I think it (at least) most of the PVs: https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/srs_amplifiers.py

**Comment by prjemian** [comment]
This is support for the synApps implementation in EPICS.  Thus, it goes into `synApps/`.
