### ISSUE TITLE
support slit objects from synApps

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#567]
question:
> are 4 blades slits pseudo motors (29idb:Slit1Hsize.VAL, 29idb:Slit1Hcenter.VAL etc) already somewhere in bluesky or do I just do soft motors like I did with my 4C motors?

response:
> no predefined object yet, you've got to make it yourself at this time

support various slit databases from synApps as ophyd Devices

@rodolakis - Thanks for the question!

**Comment by prjemian** [comment]
note: https://github.com/rodolakis/macros_29id/blob/main/IEX_29id/devices/slits.py

**Comment by prjemian** [comment]
note: https://github.com/APS-4ID-POLAR/ipython-polar/blob/6f757e7b861dd5fa73e84a10f8ae0c2877970a3c/profile_bluesky/startup/instrument/devices/slits.py

**Comment by prjemian** [comment]
In the synApps [optics](https://github.com/epics-modules/optics/tree/master/opticsApp/Db) module, these slit databases:

* [`2slit.db`](https://github.com/epics-modules/optics/blob/master/opticsApp/Db/2slit.db)
* [`2slit_soft.vdb`](https://github.com/epics-modules/optics/blob/master/opticsApp/Db/2slit_soft.vdb)
* [`xia_slit.db`](https://github.com/epics-modules/optics/blob/master/opticsApp/Db/xia_slit.db)

**Comment by prjemian** [comment]
Two general cases for hardware control of slits:

1. control of size (gap) and center: `SlitGapCenterControl`
2. control of each blade (XIA slits are an example):  `SlitBladeControl`

Most slits at APS are 2-D with each dimension having the same type of hardware control.  Propose implementing each of these two cases as a subclass of [`ophyd.PseudoPositioner`](https://github.com/bluesky/ophyd/blob/df60483867e521dcda83648756cab8fc7b80dd17/ophyd/pseudopos.py#L305).

**Comment by prjemian** [comment]
Dimensions could be either `x, y`, `h, v`, or `horizontal, vertical`.  Must the choice be made now or can it be left to the end user?  Same for the names of each blade (`top`, `up`, `left`, 'inb', `inboard`, `bot`, `bottom`, `down`, ...).

**Comment by rodolakis** [comment]
I personally have a strong preference for:

- hsize, vsize, hcenter, vcenter (match the PV names)

-  in/out, top/bot (no confusion possible)

**Comment by prjemian** [comment]
@rodolakis : `in` is a reserved python word, others use `inb` -- OK for you, too?

**Comment by prjemian** [comment]
Example setup:

```python
# SlitBase will be a subclass of PseudoPositioner
# SlitSizeCenterTransforms provides forward() and inverse() calculations

# User will define slit using preferred terminology

class SlitSizeCenterVertical(SlitSizeCenterTransforms, SlitBase):

    _pseudo = ["size", "center"]  # order is important!
    size = Component(PseudoSingle)
    center = Component(PseudoSingle)

    _real = ["bot", "top"]  # order is important!
    bot = Component(EpicsMotor, "m1")
    top = Component(EpicsMotor, "m2")


class SlitSizeCenterHorizontal(SlitSizeCenterTransforms, MySlitBase):

    _pseudo = ["size", "center"]  # order is important!
    size = Component(PseudoSingle)
    center = Component(PseudoSingle)

    _real = ["inb", "out"]  # order is important!
    inb = Component(EpicsMotor, "m3")
    out = Component(EpicsMotor, "m4")


class FRSlit(Device):

    h = Component(SlitSizeCenterHorizontal, "")
    v = Component(SlitSizeCenterVertical, "")
```

create a slit:

```python
slit = FRSlit("gp:", name="slit")
slit.wait_for_connection()
```

Calculate (horizontal) gap & center from in & out motor positions:

```python
slit.h.inverse((7, 8))
```

Calculate (vertical) gap & center from bot & top motor positions:

```python
slit.v.forward((5, 6))
```

Exercise it a bit:

```python
print(f"{slit.h.position=}  {slit.v.position=}")
slit.v.move(.1, 0)  # vertical slit: size=.1, center=0
print(f"{slit.h.position=}  {slit.v.position=}")

# set individual items
slit.h.size.move(.1)
slit.h.center.move(.1)
print(f"{slit.h.position=}  {slit.v.position=}")

# set slit size and center together
slit.h.move(.2, 0.5)
print(f"{slit.h.position=}  {slit.v.position=}")
```

Gives this output (with some noisy diagnostics added _temporarily_):

```python
slit.h.position=(0.19999999999999996, 0.5)  slit.v.position=(0.1, 0.0)
forward: pseudo_pos=SlitSizeCenterVerticalPseudoPos(size=0.1, center=0)
forward: gap_size=0.1  center=0
inverse: inb_bot=-0.05  out_top=0.05
forward: pseudo_pos=SlitSizeCenterVerticalPseudoPos(size=0.1, center=0)
forward: gap_size=0.1  center=0
inverse: inb_bot=-0.05  out_top=0.05
inverse: inb_bot=0.4  out_top=0.6
inverse: inb_bot=-0.05  out_top=0.05
slit.h.position=(0.19999999999999996, 0.5)  slit.v.position=(0.1, 0.0)
inverse: inb_bot=0.4  out_top=0.6
forward: pseudo_pos=SlitSizeCenterHorizontalPseudoPos(size=0.1, center=0.5)
forward: gap_size=0.1  center=0.5
inverse: inb_bot=0.4  out_top=0.6
forward: pseudo_pos=SlitSizeCenterHorizontalPseudoPos(size=0.1, center=0.5)
forward: gap_size=0.1  center=0.5
inverse: inb_bot=0.42  out_top=0.6
inverse: inb_bot=0.42  out_top=0.58
inverse: inb_bot=0.45  out_top=0.58
inverse: inb_bot=0.45  out_top=0.55
inverse: inb_bot=0.45  out_top=0.55
forward: pseudo_pos=SlitSizeCenterHorizontalPseudoPos(size=0.1, center=0.1)
forward: gap_size=0.1  center=0.1
inverse: inb_bot=0.45  out_top=0.55
forward: pseudo_pos=SlitSizeCenterHorizontalPseudoPos(size=0.1, center=0.1)
forward: gap_size=0.1  center=0.1
inverse: inb_bot=0.43  out_top=0.55
inverse: inb_bot=0.43  out_top=0.53
inverse: inb_bot=0.36  out_top=0.53
inverse: inb_bot=0.36  out_top=0.46
inverse: inb_bot=0.26  out_top=0.46
inverse: inb_bot=0.26  out_top=0.36
inverse: inb_bot=0.16  out_top=0.36
inverse: inb_bot=0.16  out_top=0.26
inverse: inb_bot=0.08  out_top=0.26
inverse: inb_bot=0.08  out_top=0.18
inverse: inb_bot=0.05  out_top=0.18
inverse: inb_bot=0.05  out_top=0.15
inverse: inb_bot=0.05  out_top=0.15
inverse: inb_bot=0.05  out_top=0.15
inverse: inb_bot=-0.05  out_top=0.05
slit.h.position=(0.09999999999999999, 0.1)  slit.v.position=(0.1, 0.0)
forward: pseudo_pos=SlitSizeCenterHorizontalPseudoPos(size=0.2, center=0.5)
forward: gap_size=0.2  center=0.5
inverse: inb_bot=0.05  out_top=0.15
forward: pseudo_pos=SlitSizeCenterHorizontalPseudoPos(size=0.2, center=0.5)
forward: gap_size=0.2  center=0.5
inverse: inb_bot=0.07  out_top=0.15
inverse: inb_bot=0.07  out_top=0.17
inverse: inb_bot=0.14  out_top=0.17
inverse: inb_bot=0.14  out_top=0.24
inverse: inb_bot=0.24  out_top=0.24
inverse: inb_bot=0.24  out_top=0.34
inverse: inb_bot=0.33  out_top=0.34
inverse: inb_bot=0.33  out_top=0.44
inverse: inb_bot=0.39  out_top=0.44
inverse: inb_bot=0.39  out_top=0.53
inverse: inb_bot=0.4  out_top=0.53
inverse: inb_bot=0.4  out_top=0.59
inverse: inb_bot=0.4  out_top=0.6
inverse: inb_bot=0.4  out_top=0.6
inverse: inb_bot=0.4  out_top=0.6
inverse: inb_bot=-0.05  out_top=0.05
slit.h.position=(0.19999999999999996, 0.5)  slit.v.position=(0.1, 0.0)
```

**Comment by prjemian** [comment]
NOTE: [training IOC](https://github.com/prjemian/epics-docker/blob/ac241362737ca4f04b2c53efbc8613efda4f924e/v1.1/n5_custom_synApps/ioc_files/customize_xxx.sh#L93-L95) provides 1 set of 2-D slits using 2slit.db:

```
optics.iocsh:dbLoadRecords("$(OPTICS)/opticsApp/Db/2slit.db","P=$(PREFIX),SLIT=Slit1V,mXp=m41,mXn=m42,RELTOCENTER=0")
optics.iocsh:dbLoadRecords("$(OPTICS)/opticsApp/Db/2slit.db","P=$(PREFIX),SLIT=Slit1H,mXp=m5,mXn=m6,RELTOCENTER=0")
```

**Comment by prjemian** [comment]
DEVELOPER NOTE: due to [configuration problems in the training IOC](https://github.com/prjemian/epics-docker/issues/46), can  only test using prefix `$(IOC):Slit1V` (note no trailing `:`).  With `IOC=gp:`, PVs: `gp:Slit1Vsize` and `gp:Slit1Vcenter` (for now).

**Comment by rodolakis** [comment]
Sure, that works


Fanny Rodolakis | 29-ID IEX Beamline Scientist

a.k.a. Fanny Simoes

Advanced Photon Source | Argonne National Laboratory
9700 S Cass Avenue, Bldg. 437-D004, Argonne IL 60439
Office: (630) 252-6817 | Beamline: (630) 252-2601
Email: ***@***.******@***.***> | 29-ID Website<https://www.aps.anl.gov/Sector-29/29-ID>

________________________________

**Comment by prjemian** [comment]
@rodolakis : Good.  The support above is for a slit with two EPICS motors and no underlying EPICS slit support.  Been working on the `2slit.db` support today.

**Comment by prjemian** [comment]
Similarly with the `2slit.db` support, you'll be able to use preconfigured or custom names for the parts:

### Preconfigured names : `slit1 = Optics2Slit_HV("gp:Slit1", name="slit1")`

```
h                    Optics2SlitDimension('slit1_h')
h.xn                 SlitPVPositioner    ('slit1_h_xn')
h.xp                 SlitPVPositioner    ('slit1_h_xp')
h.size               SlitPVPositioner    ('slit1_h_size')
h.center             SlitPVPositioner    ('slit1_h_center')
v                    Optics2SlitDimension('slit1_v')
v.xn                 SlitPVPositioner    ('slit1_v_xn')
v.xp                 SlitPVPositioner    ('slit1_v_xp')
v.size               SlitPVPositioner    ('slit1_v_size')
v.center             SlitPVPositioner    ('slit1_v_center')
```

### Custom names : `s2 = Optics2Slit_InbOutBotTop(gp:Slit1", name="s2")`

```
inb                  SlitPVPositioner    ('s2_inb')
out                  SlitPVPositioner    ('s2_out')
hsize                SlitPVPositioner    ('s2_hsize')
hcenter              SlitPVPositioner    ('s2_hcenter')
bot                  SlitPVPositioner    ('s2_bot')
top                  SlitPVPositioner    ('s2_top')
vsize                SlitPVPositioner    ('s2_vsize')
vcenter              SlitPVPositioner    ('s2_vcenter')
```

**Comment by prjemian** [comment]
In either case, each of the moveables is a _positioner_ so you use the `.move(target_value)` method to change position and the `.position` property to get the current position.

Use `slit1.h.sync.put(1)` or `s2.hsync.put(1)`, respectively, to sync the horizontal slits.  Similar for vertical.
