### ISSUE TITLE
BUG: conda install requirement of `apstools>=1.5.3` fails on Windows - pip successful

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#568]
Discovered that with a conda install requirement of `apstools>=1.5.3`, conda was not able to resolve all dependencies for Windows. (Found this by selective removal of packages from environment until successful install.)  Was able to install latest `apstools` via pip.

_Originally posted by @prjemian in https://github.com/BCDA-APS/use_bluesky/issues/111#issuecomment-962465402_

**Comment by gfabbris** [comment]
Is it because of `aps-dm-api`? #561

**Comment by prjemian** [comment]
That is a distinct possibility, which would push this to the 1.6.0 since it would mean a breaking change.

**Comment by prjemian** [comment]
> [9:08 AM] Rodolakis, Fanny M.
>     I install the mac version on my mac and that worked (I have apstools 1.5.3); 

@rodolakis: Thanks!

**Comment by gfabbris** [comment]
@rodolakis: what is your python version? The 1.5.3 does install in my Mac, but only if python <= 3.7. Even if I install it in an environment with a newer version, conda will downgrade it to 3.7.

**Comment by rodolakis** [comment]
I'm all good, I was just not running what I thought (too many aliases, config etc...)

**Comment by prjemian** [comment]
See if the 1.5.4 release fixes this.  Pushing to the next milestone *after* the 1.5.4 release.

**Comment by prjemian** [comment]
Released [1.5.4](https://github.com/BCDA-APS/apstools/releases/tag/1.5.4) yesterday.  Try again in `Anaconda Powershell prompt`:

    conda create -n test "apstools>=1.5.3"

**Comment by prjemian** [comment]
Pin the python version, still fails:

```
(base) PS C:\Users\Pete>  conda create -n test "apstools>=1.5.3" "python>=3.7,<3.8"  -c defaults -c conda-forge -c aps-anl-tag
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining apstools[version='>=1.5.3']:  75%|█████████████████████████████████████████████████████████                   | 3/4 [00:00<00:00,  3.11it/s]/failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
apstools[version='>=1.5.3'] -> python[version='>=3.7|>=3.7,<3.8']
python[version='>=3.7,<3.8']
apstools[version='>=1.5.3'] -> bluesky[version='>=1.6.7'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.6|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0|>=3.10,<3.11.0a0|3.4.*']
```

**Comment by prjemian** [comment]
To test, a tag is necessary: 1.6.0rc#

**Comment by prjemian** [comment]
Tagged [1.6.0rc3](https://github.com/BCDA-APS/apstools/releases/tag/1.6.0rc3) to test in windows.  Once that pubkishes to anaconda.org, then test with:

    conda create -n test "apstools>=1.6" -c defaults -c conda-forge -c aps-anl-tag

**Comment by prjemian** [comment]
This worked but `apstools>=1.6` failed.  Probably because only _release candidates_ are available.

    conda create -n test "apstools>1.5.4" --force -y -c defaults -c conda-forge -c aps-anl-tag

This worked!
