### ISSUE TITLE
unexpected key in datum_kwargs

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#651]
This unexpected key in `datum_kwargs`: https://github.com/BCDA-APS/apstools/blob/d95da4539c21540c82352d42b7a84a64eeb5a9af/apstools/devices/area_detector_support.py#L364-L365

triggers an exception when trying to read the image data using databroker.

Just remove it (or comment it out).

**Comment by prjemian** [comment]
@gfabbris, @QZhang234: Agree?

**Comment by gfabbris** [comment]
Yes, I think we need to just remove it. I don't quite understand how, but seems like it handles the filename independently from the datum_kwargs.
