### ISSUE TITLE
PVPositionerSoftDone gets stuck if target position is the same as current position

### ISSUE THREAD

**Issue by gfabbris** [BCDA-APS/apstools#725]
I ran into this problem with a couple of devices that use `PVPositionerSoftDone`. I think this is because if the `position` is the same as the current value in:

https://github.com/BCDA-APS/apstools/blob/c52de8902827955160e56ff25a9345559422784a/apstools/devices/positioner_soft_done.py#L191

Then `cb_setpoint` is not called, and `done` is never switched to `False`.

**Comment by prjemian** [comment]
@gfabbris Thanks for reporting.  I'll also add unit test(s) for this.

**Comment by prjemian** [comment]
Perhaps we see the same problem with this existing unit test code: https://github.com/BCDA-APS/apstools/blob/d062549a3e2a0bdd10808f2aeabb8f9212743248/apstools/devices/tests/test_positioner_soft_done.py#L359

It was succeeding locally but failing in GitHub Actions, so it was _localized_ (`test_move_calcpos[12] SKIPPED (need --run-local option to run)`) using: https://github.com/BCDA-APS/apstools/blob/d062549a3e2a0bdd10808f2aeabb8f9212743248/apstools/devices/tests/test_positioner_soft_done.py#L344

**Comment by prjemian** [comment]
@gfabbris Here's my test code.  It's not failing for me locally. Suggestions?  Meanwhile, I'll start a PR so GHA will run the tests.
https://github.com/BCDA-APS/apstools/blob/e089f3f8b0467dd16233ba713d639b348ad61b01/apstools/devices/tests/test_issue725.py#L7-L30

**Comment by prjemian** [comment]
GHA ran.  This is the same error you saw @gfabbris ?

```py
    def test_same_position_725(target, calcpos):
        # Before anything is changed.
        confirm_in_position(calcpos)
    
        # Confirm the initial position is as expected.
        if calcpos.position == target:
            # First, move away from the target.
            status = calcpos.move(-target or 0.1 * (1 + random.random()))
            assert status.done
            assert status.elapsed > 0, str(status)
>           confirm_in_position(calcpos)

/home/runner/work/apstools/apstools/apstools/devices/tests/test_positioner_soft_done.py:384: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

positioner = PVPositionerSoftDoneWithStop(prefix='', name='calcpos', settle_time=0.0, timeout=None, read_attrs=['readback', 'setpoint'], configuration_attrs=['done', 'tolerance', 'target'], limits=None, egu='')

    def confirm_in_position(positioner):
        """Apply the 'inposition' property code."""
        reading = positioner.read()
        p = reading[positioner.setpoint.name]["value"]
        r = reading[positioner.readback.name]["value"]
        t = positioner.actual_tolerance
>       assert abs(r - p) <= t, f"target={p}, readback={r}, tolerance={t}"
E       AssertionError: target=0.1548780125648433, readback=0.0, tolerance=1e-05
E       assert 0.1548780125648433 <= 1e-05
E        +  where 0.1548780125648433 = abs((0.0 - 0.1548780125648433))

/home/runner/work/apstools/apstools/apstools/devices/tests/test_positioner_soft_done.py:261: AssertionError
=============================== warnings summary ===============================
```

**Comment by gfabbris** [comment]
I think I understand this bug. The issue seems to be when the `EpicsSignal` uses a `write_pv` that is different from the "read" pv, as for instance in the [Lakeshore 336](https://github.com/BCDA-APS/apstools/blob/fddc9729d70fba31a9e8b750a64fd75c067fe19a/apstools/devices/lakeshore_controllers.py#L46):

```python
In [25]: lakeshore336.loop2.setpoint._write_pv
Out[25]: <PV '4idd:LS336:TC3:OUT2:SP', count=1, type=time_double, access=read/write>

In [26]: lakeshore336.loop2.setpoint._read_pv
Out[26]: <PV '4idd:LS336:TC3:OUT2:SP_RBV', count=1, type=time_double, access=read/write>
```

Then, the `setpoint.put` does not run the `SUB_DONE` callback because [this line](https://github.com/bluesky/ophyd/blob/0e8acb3df3d17e0ab7aa2cc924831f4a0c580449/ophyd/signal.py#L2081) doesn't run since `self.pvname != self.setpoint_pvname`.

**Comment by prjemian** [comment]
What would be the consequence if the `lakeshore336.loop2.setpoint` was changed to `EpicsSignal("{prefix}OUT{loop_number}:SP", ...)`?  (Ignoring the read PV)

**Comment by prjemian** [comment]
Or, ... it's just a matter of satisfying `self.pvname == self.setpoint_pvname` which you could set from the command line.

**Comment by gfabbris** [comment]
Yes, this solves the problem in the lakeshore. But it is a more general problem, I had another device that used `PVPositionerSoftDone` that had the same issue. My understanding is that the real bug is in `EpicsSignal`, because it should run the "sub_value" regardless of a separate write_pv being given or not.

For apstools, I would prefer to add a `self.cb_setpoint()` in the `PVPositionerSoftDone._setup_move` since that will fix the issue regardless of how the setpoint is configured.

**Comment by prjemian** [comment]
Can you add code proposing that?

**Comment by gfabbris** [comment]
Here it is: [e91fa01](https://github.com/BCDA-APS/apstools/pull/730/commits/e91fa01a6797766d4a72c367917ef45a3fb3f4e3).

Should we bring this up with the Bluesky team? We could double check this before, but I think this is not the expected behavior for `EpicsSignal`.

**Comment by prjemian** [comment]
> Should we bring this up with the Bluesky team?

Yes
