### ISSUE TITLE
Are yml files missing from packaging?

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#732]
User sends by email:

> I was on 1.6.3 because when I installed 1.6.5 from conda-forge it complained about missing some yml files. Installing from source does not have the same issue.

Similar report about pip.

Investigate.

**Comment by prjemian** [comment]
`from apstools.devices.aps_undulator import ApsUndulator` triggers the problem

Anything that tries to import the aps cycle code, specifically.  Any `import apstools.devices`

**Comment by prjemian** [comment]
`tar tjf /home/prjemian/micromamba/pkgs/apstools-1.6.5-pyhd8ed1ab_0.tar.bz2 | grep yml` - Missing from conda package.

**Comment by prjemian** [comment]
```bash
python -m setup build sdist
tar tzf ./dist/apstools-1.6.6.dev16+g31e0816.tar.gz | grep yml
```

shows

```
apstools-1.6.6.dev16+g31e0816/.github/publish_anaconda.yml
apstools-1.6.6.dev16+g31e0816/.github/workflows/publish-docs.yml
apstools-1.6.6.dev16+g31e0816/.github/workflows/unit_tests.yml
apstools-1.6.6.dev16+g31e0816/.github/workflows/upload-pypi.yml
apstools-1.6.6.dev16+g31e0816/apstools/devices/aps_cycle_info.yml
apstools-1.6.6.dev16+g31e0816/environment.yml
```

File `aps_cycle_info.yml` is there, the others should not be packaged.

**Comment by prjemian** [comment]
Per [setuptools-scm documentation](https://github.com/pypa/setuptools_scm/blob/1b18371fc2fa672f39c758a103c4d12956b5964f/README.rst#setuptools_scm):

> Unwanted files must be excluded by discarding them via MANIFEST.in.

[`MANIFEST.in`](https://github.com/pypa/setuptools_scm/blob/07270fcc188757289818915345e583a9d3dd69a0/MANIFEST.in) from `setuptools-scm`:

```
exclude *.nix
exclude .pre-commit-config.yaml
exclude .git_archival.txt
include *.py
include testing/*.py
include tox.ini
include *.rst
include LICENSE
include *.toml
include mypy.ini
include testing/Dockerfile.busted-buster
recursive-include testing *.bash
```

**Comment by prjemian** [comment]
> `MANIFEST.in` may still be used: anything defined there overrides the hook. This is mostly useful to exclude files tracked in your SCM from packages, although in principle it can be used to explicitly include non-tracked files too.

**Comment by prjemian** [comment]
This [table](https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands) is useful when editing the `MANIFEST.in` file.

**Comment by canismarko** [comment]
@prjemian I tried the same steps as yesterday on our call with the 1.6.6rc1, and get the same error: https://gist.github.com/canismarko/90200e083b1663b03c51ea129c2ce052
