### ISSUE TITLE
listruns could search hints for keys

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#776]
@strempfer requests (by email):

> The apstools routine `listruns()` does not extract values from the hints. Could you please add something like shown below to also get access to the keys like `monitor` and `scan_type` stored in hints?

```py
from apstools.utils import ListRuns
import pandas as pd

def listscans(cat=None, ids=[-2, 131, ], keys="scan_id scan_type monitor detectors"):
    lr = ListRuns(cat=cat)
    lr.ids = ids
    _keys = keys.split()
 
    _hints=False
    if 'hints' not in _keys:
        _keys.append('hints')
        _hints=True

    lr.keys = _keys
    r = lr.parse_runs()
    empty = {i for i in r if r[i]==['','']}
    for i in empty:
        r[i]=[r['hints'][0][i],r['hints'][0][i]]
    if _hints:
        r.pop('hints')
 
    print(f"{pd.DataFrame(r)}") 
```

> An alternative would be we create a routine `listscans()` in polartools similar to above. What do you think is better?

**Comment by prjemian** [comment]
@strempfer This could be more general than polartools.  Can you provide my (by email or Teams) the uid of a run or two to be used for development and testing?

**Comment by prjemian** [comment]
First round at your code produces an exception:

```py
def listscans(cat=None, ids=[-2, 131, ], keys="scan_id scan_type monitor detectors"):
    lr = ListRuns(cat=cat)
    lr.ids = ids
    _keys = keys.split()
 
    lr.keys = _keys
    if 'hints' not in _keys:
        lr.keys.append("hints")

    r = lr.parse_runs()
    empty = {i for i in r if r[i]==['','']}
    for i in empty:
        r[i]=[r['hints'][0][i],r['hints'][0][i]]
    if 'hints' not in _keys:
        r.pop('hints')
 
    print(f"{pd.DataFrame(r)}") 
```

the run it

```ipython
In [71]: listscans(ids=[-1, -2])
KeyError: 'monitor'
```

**Comment by prjemian** [comment]
@strempfer What is happening in this code?

```py
    empty = {i for i in r if r[i]==['','']}
    for i in empty:
        r[i]=[r['hints'][0][i],r['hints'][0][i]]
```

I'm looking at a structure like this:

```py
In [72]: r
Out[72]: 
{'scan_id': [386, 385],
 'scan_type': ['', ''],
 'monitor': ['', ''],
 'detectors': [['adsimdet', 'scaler1'], ['scaler1']],
 'hints': [{'gridding': 'rectilinear',
   'dimensions': [[['m1'], 'primary'], [['m2'], 'primary']]},
  {'dimensions': [[['time'], 'primary']]}]}
```

**Comment by prjemian** [comment]
Looks as if the index is inside-out.  The length of each value in `r` is `len(ids)`.  This is coded for two scan ids: `r[i]==['','']`, so is this code: `r[i]=[r['hints'][0][i],r['hints'][0][i]]`

So, you want to replace the existing dictionary keys for `scan_type` and `monitor` if they are 
So, for the existing dictionary keys for `scan_type` and `monitor`, replace empty content (`''`) with content found in `hints` (if it is given).  Right?

**Comment by prjemian** [comment]
revised code:

```py
def listscans(cat=None, ids=[-2, 131, ], keys="scan_id scan_type monitor detectors"):
    lr = ListRuns(cat=cat)
    lr.ids = ids
    _keys = keys.split()

    lr.keys = list(_keys)
    if 'hints' not in _keys:
        lr.keys.append("hints")

    r = lr.parse_runs()

    for item in _keys:
        if item not in r:
            # if the item is not in the dictionary
            r[item] = ["" for i in range(len(ids))]
        for i in range(len(ids)):  # edit the dictionary
            if r[item][i] == "" and item in r["hints"][i]:
                # fill empty values from hints, if available
                r[item][i] = r["hints"][i][item]

    if 'hints' not in _keys:
        r.pop('hints')

    print(f"{pd.DataFrame(r)}")
```

when run, gives:

```py
In [130]: listscans(ids=[-1, -2, -3])
   scan_id scan_type monitor            detectors
0      386                    [adsimdet, scaler1]
1      385                              [scaler1]
2      384                             [adsimdet]
```

**Comment by strempfer** [comment]
works great

**Comment by prjemian** [comment]
With the runs you identified:

```py
In [10]: listscans(ids=[403, 404, 415])
   scan_id scan_type   monitor                                       detectors
0      403     ascan  Ion Ch 4                                       [scalerd]
1      404    qxscan  Ion Ch 4  [scalerd, undulator_downstream_energy, pr2_th]
2      415     ascan      Time                                       [scalerd]

In [11]: run = cat[415]

In [12]: run.metadata["start"]["hints"]
Out[12]: 
{'dimensions': [[['mono_thf2'], 'primary']],
 'monitor': 'Time',
 'detectors': ['Ion Ch 4'],
 'scan_type': 'ascan'}

In [13]: run = cat[404]

In [14]: run.metadata["start"]["hints"]
Out[14]: 
{'dimensions': [[['energy'], 'primary']],
 'monitor': 'Ion Ch 4',
 'detectors': ['Ion Ch 5'],
 'scan_type': 'qxscan'}
```

@strempfer : Regarding `detectors` (and other possibly hinted keys), which should take precedence?  As-is, or override from `hints` if specified?

**Comment by prjemian** [comment]
That is, replace:

```py
            if runs[k][i] == "" and k in runs["hints"][i]:
```

with

```py
            if k in runs["hints"][i]:
```

**Comment by prjemian** [comment]
which returns:

```py
In [16]: listscans(ids=[403, 404, 415])
   scan_id scan_type   monitor   detectors
0      403     ascan  Ion Ch 4  [Ion Ch 5]
1      404    qxscan  Ion Ch 4  [Ion Ch 5]
2      415     ascan      Time  [Ion Ch 4]
```

**Comment by strempfer** [comment]
[Ion Ch 5] is certainly more useful information for the user than [scalerd]. What about a debugging flag like hints=False as an argument?


From: Pete R Jemian ***@***.***>
Date: Tuesday, January 10, 2023 at 10:13 AM
To: BCDA-APS/apstools ***@***.***>
Cc: Strempfer, Joerg ***@***.***>, Mention ***@***.***>
Subject: Re: [BCDA-APS/apstools] listruns could show hints (Issue #776)

which returns:

In [16]: listscans(ids=[403, 404, 415])

   scan_id scan_type   monitor   detectors

0      403     ascan  Ion Ch 4  [Ion Ch 5]

1      404    qxscan  Ion Ch 4  [Ion Ch 5]

2      415     ascan      Time  [Ion Ch 4]

**Comment by prjemian** [comment]
Not quite certain what action to be taken with `hints=False` (or `True`).  Could `hints=False` mean that hints key should not override when value `!= ""`?

Such as this code (which also renames to `hints_override`):

```py
        for i in range(len(ids)):  # edit the dictionary
            if k in runs["hints"][i]:  # hinted value available?
                if runs[k][i] == "" or hints_override:
                    # replace with value from hints
                    runs[k][i] = runs["hints"][i][k]
```

**Comment by strempfer** [comment]
Looks good. What about simply this?
        for i in range(len(ids)):  # edit the dictionary
            if hints_overwrite and item in r["hints"][i]:
                # fill empty values from hints, if available
                r[item][i] = r["hints"][i][item]



From: Pete R Jemian ***@***.***>
Date: Tuesday, January 10, 2023 at 10:37 AM
To: BCDA-APS/apstools ***@***.***>
Cc: Strempfer, Joerg ***@***.***>, Mention ***@***.***>
Subject: Re: [BCDA-APS/apstools] listruns could show hints (Issue #776)

Not quite certain what action to be taken with hints=False (or True). Could hints=False mean that hints key should not override when value != ""?

Such as this code (which also renames to hints_override):

        for i in range(len(ids)):  # edit the dictionary

            if k in runs["hints"][i]:  # hinted value available?

                if runs[k][i] == "" or hints_override:

                    # replace with value from hints

                    runs[k][i] = runs["hints"][i][k]

**Comment by prjemian** [comment]
I like the case where a requested is only found in the hints, thus the overwrite from hints if the value was empty.

**Comment by prjemian** [comment]
@strempfer, @gfabbris  -- I'm trying to understand how `run.metadata["start"]["hints"]["monitor"]` and `run.metadata["start"]["hints"]["detectors"]` are created.  This [issue comment](https://github.com/APS-4ID-POLAR/polartools/pull/42#issuecomment-804447204) suggests these might be assigned automatically.

How are these keys added to a run's `hints`?

**Comment by gfabbris** [comment]
We have a [counters class](https://github.com/APS-4ID-POLAR/ipython-polar/blob/c8cec93b87ce52ff64ca35d9e8d82bec023119a5/profile_bluesky/startup/instrument/utils/counters_class.py#L8) that keeps track of which devices are being used as "detectors" and "monitor" (within bluesky this is used to handle live plots). These are added into the run's `hints` in our custom plans, for instance in [`ascan`](https://github.com/APS-4ID-POLAR/ipython-polar/blob/c8cec93b87ce52ff64ca35d9e8d82bec023119a5/profile_bluesky/startup/instrument/plans/local_scans.py#L228) ([lines 311-319](https://github.com/APS-4ID-POLAR/ipython-polar/blob/c8cec93b87ce52ff64ca35d9e8d82bec023119a5/profile_bluesky/startup/instrument/plans/local_scans.py#L311)).

**Comment by prjemian** [comment]
@gfabbris -- The `monitor`, `detectors`, and `scan_type` keys (of the `hints` dictionary) are specific to polartools, right?
