### ISSUE TITLE
AD.HDF1 plugin reports: ERROR: capture not supported in Single mode

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#823]
The error message `ERROR: capture not supported in Single mode` appears frequently when using the area detector HDF1 file writing plugin with Bluesky plans.  The suspected root cause is this code: https://github.com/BCDA-APS/apstools/blob/c0c6918cac84d4b207554b3ec5aa253a8c7ce7bc/apstools/devices/area_detector_support.py#L458-L463

The IOC expects that the `file_write_mode` component is set to other than `Single` **_before_** `capture` is set.  This is not possible using ophyd's Device staging procedures.  The `file_write_mode` component  must be set _before_ the HDF plugin is staged.

**Comment by prjemian** [comment]
Is `detector:HDF1:Capture` a PV which should be in the `trigger()` method and not staged?

**Comment by canismarko** [comment]
I ran into this last week, actually. Since ``stage_sigs`` is an ordered dict, I figured I should set them in order, and it worked. Seems like your solution above would do the same thing, though.

Anyway, in case it's helpful here's what I set up as a mixin, and it worked the one time I tested it at the beamline.

```
self.stage_sigs[self.file_write_mode] = WriteModes.STREAM
self.stage_sigs[self.capture] = Capture.START
self.stage_sigs[self.num_capture] = 0
```

https://github.com/spc-group/haven/blob/main/haven/instrument/area_detector.py

**Comment by prjemian** [comment]
In principle, staging of each component is [atomic](https://github.com/bluesky/ophyd/blob/97c06f6f9ac08683326ade12bcb7387978af73b2/ophyd/device.py#L666-L675): 

```py
            for sig, val in stage_sigs.items():
                self.log.debug(
                    "Setting %s to %r (original value: %r)",
                    sig.name,
                    val,
                    original_vals[sig],
                )
                sig.set(val).wait()
                # It worked -- now add it to this list of sigs to unstage.
                self._original_vals[sig] = original_vals[sig]
```

Not sure why this error comes up then.

**Comment by canismarko** [comment]
I don't know. Maybe the ``OrderedDict.update()`` doesn't preserve order when using a list of tuples? Seems like it should, though.

**Comment by prjemian** [comment]
Review (and consider for refactoring) the HDF5 plugin customizations in apstools starting from the default ophyd configuration.  Ensure that each customization is tested so that it does not introduce such errors.

**Comment by prjemian** [comment]
Take note of https://github.com/BCDA-APS/bluesky_training/issues/81

**Comment by prjemian** [comment]
Root cause was upstream: https://github.com/bluesky/ophyd/pull/1066
