### ISSUE TITLE
Make PSS Shutter devices more flexible for different beamlines

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/apstools#838]
The ApsPssShutter does not match our beamline configuration (25-ID).

The open signal is created as `{PREFIX}_Open` but should be `{PREFIX}_OPEN_EPICS` to work on our hardware. The close signal is the same (but with "Close", etc.).

Here is the subclass of ApsPssShutterWithStatus that matches our hardware: https://github.com/spc-group/haven/blob/main/haven/instrument/shutter.py

**Comment by prjemian** [comment]
Also, there are _no_ unit tests on the shutter classes.

**Comment by prjemian** [comment]
@canismarko - Looking at [the haven code](https://github.com/spc-group/haven/blob/312d3db796433c8d036655a7eac37b321c716e5a/haven/instrument/shutter.py#L13C7-L27), this looks like an unusual API signature.  I'm expecting prefix to be the first argument, such as: https://github.com/BCDA-APS/apstools/blob/199c1788435589f29bbebb2344961f278479dde0/apstools/devices/shutters.py#L495

I plan to make the API here similar, allowing for `close_pv` and `open_pv` as kwargs.

**Comment by prjemian** [comment]
As in:

```py
class ApsPssShutter(ShutterBase):

    # ...

    open_signal = FormattedComponent(EpicsSignal, "{self.open_pv}")
    close_signal = FormattedComponent(EpicsSignal, "{self.close_pv}")

    def __init__(self, prefix, *args, close_pv=None, open_pv=None, **kwargs):
        self.open_pv = open_pv or f"{prefix}Open"
        self.close_pv = close_pv or f"{prefix}Close"
        # TODO" ?? what about prefix if open_pv and/or close_pv are not None ??
        super().__init__(prefix, *args, **kwargs)

    # ...
```

The `ApsPssShutterWithStatus()` class does not need changes since it passes `close_pv` and `open_pv` as unnamed kwargs to the `super()` class.

**Comment by prjemian** [comment]
Shutter might be in `unknown` state.  CI failed for that:

```py
/home/runner/work/apstools/apstools/apstools/devices/tests/test_shutters.py:96: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

shutter = EpicsMotorShutter(prefix='gp:m16', name='shutter', read_attrs=['busy', 'signal', 'signal.user_readback', 'signal.user_...signal', 'signal.user_offset', 'signal.user_offset_dir', 'signal.velocity', 'signal.acceleration', 'signal.motor_egu'])

    def operate_shutter(shutter):
        shutter.open()
        timed_pause()
>       assert shutter.state == "open"
E       AssertionError: assert 'unknown' == 'open'
E         - open
E         + unknown
```
