### ISSUE TITLE
Make ``listdevice()`` more tolerant of unconnectable lazy signals

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/apstools#845]
All of our area detectors' plugins are missing the PoolMaxBuffers (e.g. 25idSimDet:Over1:PoolMaxBuffers) PV, but it is included as part of the ophyd plugin base class.

It's a lazy component, so normally this is not a problem. But `apstools.utils.listdevice` instantiates all of the signals so that it can report their PV's. This causes listdevice to raise an exception if one signal component cannot connect. Instead, perhaps it makes sense to put this instantiation into a ``try...except`` block?

I made this change to line 32 of https://github.com/BCDA-APS/apstools/blob/main/apstools/utils/device_info.py

```
            try:
                obj = getattr(base, k)
            except TimeoutError:
                logger.warning(f"Could not list component: {base.name}.{k}")
                continue
```

and now it prints the rest of the components as normal, along with logging a warning that the missing signal is not found.

Worth including?

If you want a PR, let me know.

**Comment by prjemian** [comment]
Example use includes this notebook  https://bcda-aps.github.io/apstools/latest/examples/de_1_adsim_hdf5_custom_names.html#ophyd

**Comment by prjemian** [comment]
@canismarko I welcome a PR on this.

**Comment by canismarko** [comment]
PR submitted: https://github.com/BCDA-APS/apstools/pull/846
