### ISSUE TITLE
Installing apstools on windows

### ISSUE THREAD

**Issue by yeticat44** [BCDA-APS/apstools#866]
Trying to install apstools 1.6.16 but it requires readline which s not on windows.

`mamba install apstools==1.6.16` returns 

> The following package could not be installed
> └─ apstools 1.6.16  is uninstallable because it requires
>    └─ readline !=8.1.2 , which does not exist (perhaps a missing channel).
> 

`pip install readline` reports readline as not meant to be installed on windows

tagging @canismarko

**Comment by prjemian** [comment]
You _might_ be successful installing by pip with the `--no-deps` kwarg.  That's an easy thing to try first.
