### ISSUE TITLE
LabJack T7 support

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/apstools#879]
I was going to work on this, but was wondering what the best way forward is.

I have a LabJack T7 that I'm using to measure voltage signals on the differential analog inputs.

Synapps 6.2.1 includes labjack support from April 2022. In Nov 2022, @MarkRivers rewrote the EPICS support to use the vendor's LJM library, so at some point (synapps 6.3?) that will be available. I haven't dug into the record enough, but I suspect that some of the PVs are different.

@kurtgoetze helped me get the old labjack support working, and I could submit a PR to provide a device for it. But would it be better to get the new version working at our beamline and then write an ophyd device for that, knowing that it won't actually be useful for people using synapps 6.2.1 or earlier?

**Comment by prjemian** [comment]
Versioned support seems reasonable (some version info as part of the device name, that is).

**Comment by prjemian** [comment]
Will we need to support both databases?

**Comment by MarkRivers** [comment]
I think that few enough Bluesky users were using the old LabJack driver that only supporting the new one makes sense.

**Comment by canismarko** [comment]
Thanks for the input. I will work on the most recent labjack support then. Once we get it working in the IOC, I'll get started on the Ophyd device.

**Comment by prjemian** [comment]
@canismarko: Any progress?

**Comment by canismarko** [comment]
> @canismarko: Any progress?

Yeah, some. I got the IOC running, and made a little progress on a device in haven for using the analog inputs to start.

I just finished something else I needed to get done before working on the labjack support more, but I should have some time soon. Sorry for the delay.

https://github.com/spc-group/haven/blob/main/src/haven/instrument/labjack.py
