### ISSUE TITLE
settling for SRS-570 Pre-amp gain settings

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/apstools#906]
I was fiddling with a plan for automatically setting the gain on an SRS-570 (using bluesky-adaptive), and noticed that the voltage at the output spikes when changing the gain, and takes up to 1-1.5 seconds to settle when in LOW NOISE or LOW DRIFT mode (~0.3 sec when in HIGH BW mode).

I'm working on modifying the relevant signals to include a settling time in the status when ``set``ting these signals.

Interested in a PR once I get it done?

**Comment by canismarko** [comment]
Stretch goal is to have the settling time change based on the mode, assuming it's consistent across devices.

Also, I'll do some tests to see how consistent this is across devices.

**Comment by prjemian** [comment]
I'm trying to get the 1.6.18 release out by the end of last week (it's overdue).  Ok if this is for the 1.6.19 release?

**Comment by canismarko** [comment]
> I'm trying to get the 1.6.18 release out by the end of last week (it's overdue). Ok if this is for the 1.6.19 release?

Sure thing. I'll implement in haven first anyway since it's easier to test there.
