### ISSUE TITLE
PVPositionerSoftDone doesn't update done value

### ISSUE THREAD

**Issue by gfabbris** [BCDA-APS/apstools#916]
We ran into an issue in using the `PVPositionerSoftDone` with the Lakeshore 340. The `RunEngine` did not recognized the motion as done (so it would keep waiting until aborted). Checking the `MoveStatus` generated by `.set`, we noticed that it was not getting updated, and then checking the `.done` signal, it did not switched to `False` in the beginning of the motion. It seems like the problem is that during `_setup_move`, the `cb_readback` is called with kwargs ([here](https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L235)), but that function will only switch the done signal to `False` if it has a `value` kwarg ([here](https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L196)). I don't understand why the `if` statement in line 194 needs to be there, but one potential solution to this is to replace line 235 to:
``` python
self.cb_setpoint(value=position)
```

**Comment by prjemian** [comment]
Possibly related to #810.

**Comment by prjemian** [comment]
https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L235

https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L196

**Comment by prjemian** [comment]
Compare https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L221-L236

with [`ophyd.PVPositionerDone._setup_move()`](https://github.com/bluesky/ophyd/blob/5c03c3fff974dc6390836fc83dae4c247a35e662/ophyd/pv_positioner.py#L592-L595):

```py
    def _setup_move(self, position: Any) -> None:
        super()._setup_move(position)
        self.done.put(0, internal=True)
        self.done.put(1, internal=True)
```

**Comment by prjemian** [comment]
The call to `super()._setup_move(position)` calls [`ophyd.PVPositioner._setup_move()`](https://github.com/bluesky/ophyd/blob/5c03c3fff974dc6390836fc83dae4c247a35e662/ophyd/pv_positioner.py#L171-L177):

```py
    def _setup_move(self, position):
        """Move and do not wait until motion is complete (asynchronous)"""
        self.log.debug("%s.setpoint = %s", self.name, position)
        self.setpoint.put(position, wait=True)
        if self.actuate is not None:
            self.log.debug("%s.actuate = %s", self.name, self.actuate_value)
            self.actuate.put(self.actuate_value, wait=False)
```

**Comment by prjemian** [comment]
> I don't understand why the `if` statement in line 194 needs to be there

Normally, `cb_setpoint()` is called by the subscription setup here: https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L138

The `if` statement handles this call: https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L235

Time to review the `_setup_move()` method: https://github.com/BCDA-APS/apstools/blob/9c0a0eecbd6319baf1d63d93bc8d01d368fefe31/apstools/devices/positioner_soft_done.py#L221-L236
