### ISSUE TITLE
Add ramp temperature and output enable to PTC-10 support

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/apstools#931]
We're testing our PTC-10 capillary heater controller. There are a few signals that would be helpful for us and maybe other beamlines? 

We'd like a PV like ``25idptc10:tc1:5A:rampTemp_RBV`` that currently doesn't appear in the device (or at least I can't find it.

I think it should be in ptc10controller.PTC10AioChannel.ramptemp:

```python
class PTC10AioChannel(Device):
   ...
    ramptemp = Component(EpicsSignalRO, "rampTemp", kind="normal")
```

We'd also like and output_enable for turning the heater on and off. Not sure how this should work with the PVPositioner class, though. Maybe there's a place for the output_enable in the pv positioner support?

```python
class PTC10PositionerMixin(...):
    ...
    output_enable = Component(EpicsSignal, "outputEnable", kind="omitted")
```

Edit: just to clarify, I think the PVs exist in the IOC, just not in the apstools device definition.

https://github.com/epics-modules/ip/blob/master/ipApp/Db/PTC10.db

https://github.com/epics-modules/ip/blob/6206afedb94db491a385ffd0c66f9223140a503e/ipApp/Db/PTC10_aio_chan.db#L163

**Comment by canismarko** [comment]
Opened an issue to discuss this with apstools repo. https://github.com/BCDA-APS/apstools/issues/931

**Comment by prjemian** [comment]
RO: [`rampTemp_RBV`](https://github.com/epics-modules/ip/blob/6206afedb94db491a385ffd0c66f9223140a503e/ipApp/Db/PTC10_aio_chan.db#L163-L172)

```
record(ai, "$(P)$(T):$(C):rampTemp_RBV") {
  field(DTYP, "stream")
  field(PINI, "YES")
  field(DESC, "$(C) Ramp Temp rbv")
  field(INP,  "@PTC10.proto getRampTemp($(C)) $(PORT) $(ADDR)")
  field(EGU,  "C")
  field(SDIS, "$(P)$(T):$(C):ioType_RBV")
  field(DISV, "0")
  field(PREC, "$(PREC=4)")
}
```
