### ISSUE TITLE
aps_cycle.py

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#970]
- https://github.com/BCDA-APS/apstools/blob/ece96632cb919c34c18bc200645189a5632fa576/apstools/devices/aps_cycle.py#L22
- https://github.com/BCDA-APS/apstools/blob/ece96632cb919c34c18bc200645189a5632fa576/apstools/devices/aps_cycle.py#L117

**Comment by prjemian** [comment]
Verify that this code works in the APS-U era.

**Comment by prjemian** [comment]
Might need the new PV gateway as environment variable.

> [Tuesday 10:52 AM] Lang, Keenan C.
> That's what I did for /net/s8iddserv/xorApps/epics/ui/startup/start_epics  to have it show the new current
 > And from my work computer
> `klang@kobold:~$ export EPICS_CA_AUTO_ADDR_LIST=no`
> `klang@kobold:~$ export EPICS_CA_ADDR_LIST="pvgatemain1.aps4.anl.gov"`
> `klang@kobold:~$ caget S-DCCT:CurrentM`
>` S-DCCT:CurrentM                -0.00471643`

**Comment by MDecarabas** [comment]
I believe the issue can be closed. This is the output when testing. Looks as expected. Let me know if there is any other specific testing you want me to run


![Image](https://github.com/BCDA-APS/apstools/assets/72196105/84096b7f-98fb-4411-9274-a95b79ade5cd)

**Comment by prjemian** [comment]
Great!  Now I see the method was actually processed in the info report.
