### ISSUE TITLE
aps_undulator.py

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#973]
- https://github.com/BCDA-APS/apstools/blob/ece96632cb919c34c18bc200645189a5632fa576/apstools/devices/aps_undulator.py#L20
- https://github.com/BCDA-APS/apstools/blob/ece96632cb919c34c18bc200645189a5632fa576/apstools/devices/aps_undulator.py#L71

--------

There are 6 types of ID:

- [x] #975
- [x] #976
- [x] #977
- [x] #978
- [x] #979
- [ ] #980

**Comment by canismarko** [comment]
I got started on this in Haven, FYI.

I want energy, gap, etc to be positioners so I diverged from the apstools version, the other signals should be fine, though.

Plan to test this on real hardware once our PV gateway gets updated.

https://github.com/spc-group/haven/blob/3d9720c59d6d8f33a3272c6fd8d880fdc67425e6/src/haven/instrument/xray_source.py#L29

**Comment by prjemian** [comment]
Need to make a list of the full set of undulators to be available.  See the `ID_Main.adl` screen from the storage ring for reference.

**Comment by prjemian** [comment]
From here:
![image](https://github.com/BCDA-APS/apstools/assets/2279984/38010a8c-0608-4336-b1d7-bff420392e07)

Choose ID_Main
![image](https://github.com/BCDA-APS/apstools/assets/2279984/200995ba-b9c6-46bc-9ae1-5bf51621e661)

**Comment by prjemian** [comment]
There are 5 types of ID:

- [ ] 2M insertion device
- [ ] 4M insertion device
- [ ] STI insertion device
- [ ] Planar insertion device
- [ ] Revolver insertion device

**Comment by prjemian** [comment]
How different are the controls (and PVs) for these different insertion devices?  Is there a common subclass?

The S29ID-IEX insertion device control screen is not like the others.
The revolver looks like it has some additions to features found in the others.

Perhaps consider the Planar as the base class, then look at 2M, 4M, STI, and Revolver as possible variations.  Might learn that all can augment a common subclass.

**Comment by prjemian** [comment]
Of these designs, only the 4M is _not_ associated with a feature beam line (or an early beam line such as 29ID).

**Comment by prjemian** [comment]
> I got started on this in Haven, FYI.
> 
> I want energy, gap, etc to be positioners so I diverged from the apstools version, the other signals should be fine, though.
> 
> Plan to test this on real hardware once our PV gateway gets updated.
> 
> https://github.com/spc-group/haven/blob/3d9720c59d6d8f33a3272c6fd8d880fdc67425e6/src/haven/instrument/xray_source.py#L29

This is for the STI insertion device (#977)?

**Comment by prjemian** [comment]
NOTE: To get to these displays, log into an account and workstation on the oxygen network and run `/usr/local/epics/bin/xfd-display &`.  I use my own account and workstation `tin`.

**Comment by canismarko** [comment]
@prjemian I'm not sure actually. I wrote it against the Planar undulator, but I don't know if that's what we have. Is there a way to know which style of undulator we have at 25-ID?

I sorted our the positioner bits. I can read the 4 positioner components, and every signal connects at 25-ID. I like the positioner approach because it makes the gap and tapers scannable.

Since we can't move our ID yet, I haven't testing any of the set() features.

https://github.com/spc-group/haven/blob/7145a93b0e2240a8e8ce242de2abbc25fb9a2db2/src/haven/instrument/xray_source.py#L40

**Comment by prjemian** [comment]
The storage ring provides an ID_Main.adl screen which color-codes all the insertion devices.  Here's a picture from the [apstools issue](https://github.com/BCDA-APS/apstools/issues/973#issuecomment-2130437020):

![image](https://github.com/BCDA-APS/apstools/assets/2279984/200995ba-b9c6-46bc-9ae1-5bf51621e661)

Show the color code of "Planar" for the ID at 25-ID.  as the screen shows, that's the most common design.

**Comment by canismarko** [comment]
Makes sense. I also confirmed this with Marty Smith. I wrote the Device class assuming a planar undulator, so that's good. Anyway, let me know if you want it turned into a PR or anything.

The positioner-style undulator device I wrote would NOT be backwards compatible with the apstools ApsUndulator Device.

**Comment by prjemian** [comment]
I recognize that the ApsUndulator is for the APS Undulator A.  Not guaranteed to be a good base class or model for APS-U.  It shares some basic ideas, but you (and we) want to make changes not.  Primarily, energy and gap will be SoftPositioner subclasses.  Most of the new undulators share this PV set.  Others, notably, the Revolver, used at 8-ID and 34-ID, is different.

**Comment by prjemian** [comment]
A PR is most welcome, for issue #978.

**Comment by gfabbris** [comment]
Pre-upgrade the undulator EPICS support did not include energy backlash motion. Does anybody know if this changed? We had to implement it in Bluesky before ([link](https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/aps_source.py)), which is not ideal.

**Comment by prjemian** [comment]
> Pre-upgrade the undulator EPICS support did not include energy backlash motion. Does anybody know if this changed? We had to implement it in Bluesky before ([link](https://github.com/APS-4ID-POLAR/ipython-polar/blob/master/profile_bluesky/startup/instrument/devices/aps_source.py)), which is not ideal.

I'll ask the group (on Teams).

**Comment by prjemian** [comment]
Only the 29ID undulator issue #980 remains now and it is lower priority.  Closing since all undulators are covered by issues.

**Comment by prjemian** [comment]
Updated `ID_Main.adl` screen:

<img width="1508" height="783" alt="Image" src="https://github.com/user-attachments/assets/9d348c17-dddc-4e4c-bc13-25913fe7104d" />
