### ISSUE TITLE
STI insertion device (13 devices, including two at 4ID)

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#977]
![image](https://github.com/BCDA-APS/apstools/assets/2279984/f1d55e03-a1f5-485b-8425-f2e20531d023)

**Comment by prjemian** [comment]
(bluesky_2024_2) jemian@otz ~/.../prjemian/hklpy2 $ ls /APSshare/adlsys/*/*/*/*/*/STI_newIDControl.adl
    /APSshare/adlsys/screens/adl/iocs/idctl/adl_BL/STI_newIDControl.adl  /APSshare/adlsys/screens/adl/iocs/idctl/adl_New/STI_newIDControl.adl

**Comment by prjemian** [comment]
The two files are identical (timestamp, size, cksum).

```bash
 $ grep chan= /APSshare/adlsys/screens/adl/iocs/idctl/adl_BL/STI_newIDControl.adl
		chan="$(P):StopC.VAL"
		chan="$(P):DeviceM"
		chan="$(P):Message2M.VAL"
		chan="$(P):Message1M.VAL"
		chan="$(P):EnergyM.VAL"
		chan="$(P):GapSetC.VAL"
		chan="$(P):EnergySetC.VAL"
		chan="$(P):GapM.VAL"
		chan="$(P):LocationM"
		chan="$(P):StartC.VAL"
		chan="$(P):DeviceLimitM.VAL"
		chan="$(P):DeadbandGapC"
		chan="$(P):AccessSecurityC.VAL"
		chan="$(P):TaperGapSetC.VAL"
		chan="$(P):TaperEnergySetC.VAL"
		chan="$(P):TaperEnergyM.VAL"
		chan="$(P):TaperGapM.VAL"
		chan="$(P):HarmonicValueC"
		chan="$(P):PLCVersionM.VAL"
		chan="$(P):TotalPowerM.VAL"
		chan="$(P):AccessSecurityC"
		chan="$(P):OptimumTaperM.VAL"
		chan="$(P):STIVersionM.VAL"
		chan="$(P):DeviceMagnetM"
```

**Comment by prjemian** [comment]
Prefix for 4-ID upstream insertion device: `S04ID:USID:`.  Downstream similar, such as:

```bash
lift% caget S04ID:{U,D}SID:DeviceM
S04ID:USID:DeviceM             APS30#4
S04ID:DSID:DeviceM             APS30#9
```

**Comment by prjemian** [comment]
Energy | upstream | downstream
--- | --- | ---
setpoint | `S04ID:USID:EnergySetC` 11.3812 | `S04ID:DSID:EnergySetC` 140
readback| `S04ID:USID:EnergyM` 11.3812 | `S04ID:DSID:EnergyM` 11.3812

**Comment by prjemian** [comment]
Curious.  Today, the _gap control_ screen for 04US, as started from the `ID_Main.adl` screen, is for the Planar undulator PVs, using the S04US PVs.
![image](https://github.com/BCDA-APS/apstools/assets/2279984/9ca2da26-7d99-4582-a94a-3306ddd75e6d)

Digging around a bit, I found the STI screen and compared.  From the user perspective, the controls seem identical.  Let's start the ophyd Device for the STI using the same pattern as for Planar.

```py
class PlanarUndulator(ID_Spectrum_Mixin, ID_Controls_Mixin, ID_Misc_Mixin, Device):
    """Same PVs as APS Planar Undulator."""
```

**Comment by gfabbris** [comment]
As far as I understand the STI undulators are all planar undulators, but are produced by STI Optronics instead of in-house.

**Comment by prjemian** [comment]
I'm OK with the part on which I commented.  I'll leave it to Tom for the PR review.
